apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: myapp
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: 80
      {{- if eq .Values.serviceType "NodePort" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
