apiVersion: v2               # Helm chart API version
name: mynginxapp                  # Name of the chart
version: 0.1.0               # Chart version (change when updating chart)
description: Simple Helm chart for learning
appVersion: "1.0"            # Application version (for your container image) i.e nginx version
