replicaCount: 1

image:
  repository: nginx
  tag: latest

cpuRequest: 100m
memoryRequest: 128Mi
cpuLimit: 200m
memoryLimit: 256Mi

servicePort: 80
serviceType: NodePort      # NodePort for Dev
nodePort: 30080            # Optional, choose any free port

hpa:
  enabled: false
