replicaCount: 4

image:
  repository: nginx
  tag: stable

cpuRequest: 300m
memoryRequest: 512Mi
cpuLimit: 600m
memoryLimit: 1Gi

servicePort: 80
serviceType: LoadBalancer   # <--- LoadBalancer for Prod

hpa:
  enabled: true
  minReplicas: 4
  maxReplicas: 10
  cpuUtilization: 50
